#!/bin/bash

# ABOUT BLOCK BEGIN____________________________________________________________
# Number: 002
# Name: VAS
# Description: Bogus check
# Severity: IW
# Quality: The pattern match is weak and can fail in unexpected ways
# Notes: Used to demonstrate different group usage
# ABOUT BLOCK END______________________________________________________________

# DEBUG: Temp hack for BL pathing issues.
#cd /opt/linqc

# Source our functions
# NOTE: The path is obviously wrong. This would be a pre-determined location,
#       likely one that is fully, not relatively pathed.
if [[ -e lib/qcfunctions.bash ]]
then
    . lib/qcfunctions.bash
fi

# Validate that the sourcing was successfull
if [[ ! ${was_successfully_sourced} ]]
then
    # Not much we can do here. No telling what is going on. Exit with the
    # most appropriate error value and message for both BL and CL environment.
    echo "ERROR: Failed to source functions." >&2
    exit 1
fi

# Pull in the global config
SourceGlobalConfig

# Print the header for the test
VPrintHeader "VAS in nsswitch.conf"

# See if we should run or not
GroupCheck daily weekly

# Check for overrides
OverrideCheck

# We have to check for it, it is in a grep in the following test. That will
# hang if it does not exist.
VPrint -n "Validating that nsswitch.conf exists..."
sleep 1  # Just to simulate a long running test
if [[ ! -e /etc/nsswitch.conf ]]
then
    VPrint "none found."
    VPrint "ERROR: The nsswitch.conf file does not exist."
    QCExit ${QCRV_FAIL}
fi
VPrint "good."


VPrint -n "Checking the passwd entry..."
sleep 1  # Just to simulate a long running test
if [[ $(grep ^passwd: /etc/nsswitch.conf) == *vas4* ]]
then
    VPrint "Good."
    QCExit ${QCRV_PASS}
else
    VPrint "FAIL."
    QCExit ${QCRV_FAIL}
fi

# This is unreachable code
QCExit ${QCRV_IERR}
