#!/bin/ksh
#
# Usage Example:
# - Start in background
# spinfunc &
# - Save the PID for later use
# spinner_pid=$!
# - Run your long running process
# ...
# - stop the spinner function/process
# kill ${spinner_pid}
# 


function spinner
{
  typeset -i sv=0
  trap 'printf "\b\b...Done.\n"' EXIT

  printf "Running -"

  while :
  do
    printf "\b"

    case ${sv} in
      0) sv=1 ; printf "\\" ;;
      1) sv=2 ; printf "|"  ;;
      2) sv=3 ; printf "/"  ;;
      3) sv=0 ; printf "-"  ;;
    esac

    sleep 1
  done
}








spinner &
spinner_pid=$!

sleep 7


kill $spinner_pid

sleep 1
